# Job Application Automation Action Links

job_application_automation.add_company:
  title: 'Add Company'
  route_name: 'node.add'
  route_parameters:
    node_type: 'company'
  appears_on:
    - job_application_automation.dashboard
  weight: 0

job_application_automation.add_job_posting:
  title: 'Add Job Posting'
  route_name: 'node.add'
  route_parameters:
    node_type: 'job_posting'
  appears_on:
    - job_application_automation.dashboard
  weight: 1

job_application_automation.view_content:
  title: 'Manage All Content'
  route_name: 'system.admin_content'
  appears_on:
    - job_application_automation.dashboard
  weight: 2