<?php

/**
 * @file
 * Contains forseti_games.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function forseti_games_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.forseti_games':
      return '<p>' . t('Module for creating and hosting games on Forseti.Life') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function forseti_games_theme($existing, $type, $theme, $path) {
  return [
    'game_home' => [
      'variables' => [
        'games' => [],
      ],
    ],
    'game_block_matcher' => [
      'variables' => [
        'game_data' => [],
      ],
    ],
  ];
}
