users_metrics.settings:
  type: config_object
  label: 'Users Metrics settings'
  mapping:
    excluded_roles:
      type: sequence
      label: 'Excluded roles'
      sequence:
        type: string
        label: 'Role ID'
    excluded_uids:
      type: sequence
      label: 'Excluded user IDs'
      sequence:
        type: integer
        label: 'User ID'
