<?php

namespace Drupal\dungeoncrawler_content\Service;

/**
 * Interface for game phase handlers (Strategy pattern).
 *
 * Each game phase (exploration, encounter, downtime) implements this interface.
 * The GameCoordinatorService delegates action processing and phase lifecycle
 * to the appropriate handler based on the current game_state.phase.
 */
interface PhaseHandlerInterface {

  /**
   * Returns the machine name of this phase.
   *
   * @return string
   *   One of: 'exploration', 'encounter', 'downtime'.
   */
  public function getPhaseName(): string;

  /**
   * Returns the list of action intent types legal in this phase.
   *
   * @return string[]
   */
  public function getLegalIntents(): array;

  /**
   * Validates whether an action intent is legal in the current state.
   *
   * @param array $intent
   *   The action intent payload with keys: type, actor, target, params.
   * @param array $game_state
   *   The current game_state from dungeon_data.
   * @param array $dungeon_data
   *   The full dungeon_data payload.
   *
   * @return array
   *   ['valid' => bool, 'reason' => string|null]
   */
  public function validateIntent(array $intent, array $game_state, array $dungeon_data): array;

  /**
   * Processes an action intent and returns the result.
   *
   * @param array $intent
   *   The action intent payload with keys: type, actor, target, params.
   * @param array $game_state
   *   The current game_state (will be mutated in place).
   * @param array $dungeon_data
   *   The full dungeon_data payload (will be mutated in place).
   * @param int $campaign_id
   *   The campaign ID.
   *
   * @return array
   *   Result payload with keys:
   *   - 'success' => bool
   *   - 'result' => array (action-specific result data)
   *   - 'mutations' => array (state changes applied)
   *   - 'events' => array (events to log)
   *   - 'phase_transition' => array|null (if phase should change)
   *   - 'narration' => string|null (AI GM narration, if any)
   */
  public function processIntent(array $intent, array &$game_state, array &$dungeon_data, int $campaign_id): array;

  /**
   * Called when the game transitions INTO this phase.
   *
   * @param array $context
   *   Transition context (e.g., encounter_context for encounter phase).
   * @param array $game_state
   *   The game_state being entered (will be mutated).
   * @param array $dungeon_data
   *   The full dungeon_data payload (will be mutated).
   * @param int $campaign_id
   *   The campaign ID.
   *
   * @return array
   *   Events generated by the phase entry.
   */
  public function onEnter(array $context, array &$game_state, array &$dungeon_data, int $campaign_id): array;

  /**
   * Called when the game transitions OUT OF this phase.
   *
   * @param array $game_state
   *   The game_state being exited (will be mutated to snapshot state).
   * @param array $dungeon_data
   *   The full dungeon_data payload.
   * @param int $campaign_id
   *   The campaign ID.
   *
   * @return array
   *   Events generated by the phase exit.
   */
  public function onExit(array &$game_state, array &$dungeon_data, int $campaign_id): array;

  /**
   * Returns the set of available actions for the current state.
   *
   * Used by the client to render enabled/disabled UI controls.
   *
   * @param array $game_state
   *   The current game_state.
   * @param array $dungeon_data
   *   The full dungeon_data payload.
   * @param string|null $actor_id
   *   The entity ID of the acting character, if any.
   *
   * @return string[]
   *   List of available intent types.
   */
  public function getAvailableActions(array $game_state, array $dungeon_data, ?string $actor_id = NULL): array;

}
