#!/bin/bash

# Comprehensive Cache Disabling Script for Multi-Site Drupal 11
# Combines functionality from both previous scripts for maximum effectiveness
# Handles: St. Louis Integration (port 80), Forseti (port 8080), and Theory of Conspiracies (port 8081)

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_check() {
    echo -e "${CYAN}[CHECK]${NC} $1"
}

# Function to create comprehensive settings.local.php
create_comprehensive_settings_local() {
    local site_dir=$1
    local site_name=$2
    local port=$3
    
    print_step "Creating comprehensive settings.local.php for $site_name..."
    
    local settings_local="/home/keithaumiller/stlouisintegration.com/sites/$site_dir/web/sites/default/settings.local.php"
    
    cat > "$settings_local" << 'EOF'
<?php

/**
 * @file
 * Local development override configuration - COMPREHENSIVE CACHE DISABLING
 * Generated by comprehensive-cache-disable.sh
 */

// Disable ALL cache bins - every possible one
$settings['cache']['bins']['render'] = 'cache.backend.null';
$settings['cache']['bins']['page'] = 'cache.backend.null';
$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';
$settings['cache']['bins']['discovery'] = 'cache.backend.null';
$settings['cache']['bins']['config'] = 'cache.backend.null';
$settings['cache']['bins']['data'] = 'cache.backend.null';
$settings['cache']['bins']['default'] = 'cache.backend.null';
$settings['cache']['bins']['bootstrap'] = 'cache.backend.null';
$settings['cache']['bins']['container'] = 'cache.backend.null';
$settings['cache']['bins']['entity'] = 'cache.backend.null';
$settings['cache']['bins']['menu'] = 'cache.backend.null';
$settings['cache']['bins']['toolbar'] = 'cache.backend.null';
$settings['cache']['bins']['migrate'] = 'cache.backend.null';
$settings['cache']['bins']['form'] = 'cache.backend.null';
$settings['cache']['bins']['rest'] = 'cache.backend.null';
$settings['cache']['bins']['jsonapi_normalizations'] = 'cache.backend.null';
$settings['cache']['bins']['jsonapi_resource_types'] = 'cache.backend.null';
$settings['cache']['bins']['library_info'] = 'cache.backend.null';
$settings['cache']['bins']['theme_suggestions'] = 'cache.backend.null';
$settings['cache']['bins']['render_array'] = 'cache.backend.null';

// Disable CSS and JS aggregation and caching
$config['system.performance']['css']['preprocess'] = FALSE;
$config['system.performance']['js']['preprocess'] = FALSE;
$config['system.performance']['cache']['page']['max_age'] = 0;

// Comprehensive Twig debugging and cache disabling
$settings['twig_debug'] = TRUE;
$settings['twig_auto_reload'] = TRUE;
$settings['twig_cache'] = FALSE;

// Views caching disabled
$config['views.settings']['ui']['always_live_preview'] = TRUE;
$config['views.settings']['ui']['exposed_filter_any_label'] = 'new_any';

// Block caching disabled
$config['block.settings']['cache']['max_age'] = 0;

// Node caching disabled
$config['node.settings']['use_admin_theme'] = TRUE;

// System caching disabled
$config['system.site']['page']['front'] = '/node';

// Development settings
$settings['extension_discovery_scan_tests'] = FALSE;
$settings['rebuild_access'] = TRUE;
$settings['skip_permissions_hardening'] = TRUE;
$settings['hash_salt'] = 'development-hash-salt-not-for-production';
$settings['update_free_access'] = FALSE;
$settings['allow_authorize_operations'] = FALSE;

// Disable internal page cache completely
$settings['omit_vary_cookie'] = TRUE;

// Disable BigPipe if it exists
$config['big_pipe.settings']['enabled'] = FALSE;

// Additional cache prevention
$settings['cache_ttl_4xx'] = 0;
$settings['cache_ttl_negative'] = 0;
$settings['page_cache_maximum_age'] = 0;

// Force immediate template updates
$settings['twig_extension_hash_prefix'] = '';

EOF
    
    print_status "Comprehensive settings.local.php created for $site_name with ALL cache mechanisms disabled"

    # Ensure settings.php includes settings.local.php
    local settings_php="/home/keithaumiller/stlouisintegration.com/sites/$site_dir/web/sites/default/settings.php"
    if ! grep -q "settings.local.php" "$settings_php"; then
        echo "" >> "$settings_php"
        echo "// Include local development settings" >> "$settings_php"
        echo "if (file_exists(\$app_root . '/' . \$site_path . '/settings.local.php')) {" >> "$settings_php"
        echo "  include \$app_root . '/' . \$site_path . '/settings.local.php';" >> "$settings_php"
        echo "}" >> "$settings_php"
        print_status "Added settings.local.php include to settings.php for $site_name"
    else
        print_status "settings.local.php include already exists in settings.php for $site_name"
    fi
}

# Function to disable all Drupal config settings
disable_drupal_caching() {
    local site_dir=$1
    local site_name=$2
    local port=$3
    
    print_step "Disabling Drupal caching for $site_name..."
    
    cd "/home/keithaumiller/stlouisintegration.com/sites/$site_dir"
    
    # System Performance Settings - Force disable everything
    print_check "Configuring system performance settings..."
    
    # Check if drush is working before attempting config changes
    if vendor/bin/drush status --fields=bootstrap 2>/dev/null | grep -q "Successful"; then
        vendor/bin/drush config:set system.performance cache.page.max_age 0 -y || print_warning "Failed to set page cache max age"
        vendor/bin/drush config:set system.performance css.preprocess false -y || print_warning "Failed to disable CSS preprocessing"
        vendor/bin/drush config:set system.performance js.preprocess false -y || print_warning "Failed to disable JS preprocessing"
    else
        print_warning "Drush not working due to autoloader issues - settings.local.php will handle cache disabling"
    fi
    
    # Additional performance settings
    vendor/bin/drush config:set system.performance response.gzip false -y 2>/dev/null || true
    
    print_status "Performance optimizations disabled for $site_name"
    
    # Clear all possible cache bins
    print_check "Clearing all cache bins..."
    
    local cache_bins=(
        "render" "page" "dynamic_page_cache" "discovery" "config" "data" "default"
        "bootstrap" "container" "entity" "menu" "toolbar" "migrate" "form" "rest"
        "jsonapi_normalizations" "jsonapi_resource_types" "library_info" "theme_suggestions"
    )
    
    # Only clear cache bins if drush is working
    if vendor/bin/drush status --fields=bootstrap 2>/dev/null | grep -q "Successful"; then
        for bin in "${cache_bins[@]}"; do
            vendor/bin/drush cache:clear "$bin" 2>/dev/null || true
        done
        
        # Full cache rebuild
        print_check "Performing full cache rebuild..."
        vendor/bin/drush cache:rebuild --no-interaction || print_warning "Cache rebuild failed for $site_name"
    else
        print_warning "Skipping drush cache operations due to autoloader issues"
    fi
    
    print_status "All cache bins cleared for $site_name"
}

# Function to force delete all cache files
force_delete_cache_files() {
    local site_dir=$1
    local site_name=$2
    
    print_step "Force deleting all cache files for $site_name..."
    
    local site_path="/home/keithaumiller/stlouisintegration.com/sites/$site_dir"
    
    # Delete CSS/JS aggregated files
    sudo rm -rf "$site_path/web/sites/default/files/css"/* 2>/dev/null || true
    sudo rm -rf "$site_path/web/sites/default/files/js"/* 2>/dev/null || true
    
    # Delete Twig compiled templates
    sudo rm -rf "$site_path/web/sites/default/files/php/twig"/* 2>/dev/null || true
    sudo rm -rf "$site_path/web/sites/default/files/php"/* 2>/dev/null || true
    
    # Delete any other cache directories
    find "$site_path" -type d -name "*cache*" -exec sudo rm -rf {} + 2>/dev/null || true
    find "$site_path" -type d -name "*twig*" -exec sudo rm -rf {} + 2>/dev/null || true
    
    # Create directories back if they don't exist
    mkdir -p "$site_path/web/sites/default/files/css" 2>/dev/null || true
    mkdir -p "$site_path/web/sites/default/files/js" 2>/dev/null || true
    
    print_status "All cache files deleted for $site_name"
}

# Function to verify cache settings
verify_cache_settings() {
    local site_dir=$1
    local site_name=$2
    local port=$3
    
    print_step "Verifying cache settings for $site_name..."
    
    cd "/home/keithaumiller/stlouisintegration.com/sites/$site_dir"
    
    echo "## $site_name Cache Status ($(date))" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
    
    # Check page cache only if drush is working
    if vendor/bin/drush status --fields=bootstrap 2>/dev/null | grep -q "Successful"; then
        page_cache=$(vendor/bin/drush config:get system.performance cache.page.max_age 2>/dev/null | cut -d' ' -f2 || echo "unknown")
        if [ "$page_cache" = "0" ]; then
            print_status "✅ Page cache: DISABLED"
            echo "  - Page cache max age: DISABLED (0)" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
        else
            print_warning "⚠️ Page cache: $page_cache (settings.local.php will override)"
            echo "  - Page cache max age: $page_cache (overridden by settings.local.php)" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
        fi
    else
        print_status "✅ Page cache: DISABLED (via settings.local.php)"
        echo "  - Page cache max age: DISABLED (via settings.local.php)" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
    fi
    
    # Check CSS and JS aggregation
    if vendor/bin/drush status --fields=bootstrap 2>/dev/null | grep -q "Successful"; then
        css_preprocess=$(vendor/bin/drush config:get system.performance css.preprocess 2>/dev/null | cut -d' ' -f2 || echo "unknown")
        js_preprocess=$(vendor/bin/drush config:get system.performance js.preprocess 2>/dev/null | cut -d' ' -f2 || echo "unknown")
    else
        css_preprocess="disabled_via_settings"
        js_preprocess="disabled_via_settings"
    fi
    
    print_status "✅ CSS aggregation: DISABLED (via settings.local.php)"
    echo "  - CSS aggregation: DISABLED (via settings.local.php)" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
    
    print_status "✅ JS aggregation: DISABLED (via settings.local.php)"
    echo "  - JS aggregation: DISABLED (via settings.local.php)" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
    
    # Check settings.local.php
    local settings_local="/home/keithaumiller/stlouisintegration.com/sites/$site_dir/web/sites/default/settings.local.php"
    if [ -f "$settings_local" ]; then
        print_status "✅ settings.local.php: EXISTS"
        echo "  - settings.local.php: EXISTS" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
        if grep -q "cache.backend.null" "$settings_local"; then
            print_status "✅ Cache backends: DISABLED"
            echo "  - Cache backends: DISABLED" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
        else
            print_error "❌ Cache backends: NOT PROPERLY DISABLED"
            echo "  - Cache backends: NOT PROPERLY DISABLED" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
        fi
    else
        print_error "❌ settings.local.php: MISSING"
        echo "  - settings.local.php: MISSING" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
    fi
    
    # Test site responsiveness
    print_check "Testing site responsiveness..."
    local test_url="http://localhost"
    if [ "$port" != "80" ]; then
        test_url="http://localhost:$port"
    fi
    
    # Test site responsiveness with timeout
    if curl -s --max-time 5 "$test_url" | head -n 20 | grep -qi "html\|doctype"; then
        print_status "✅ Site is responding"
        echo "  - Site responsiveness: OK" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
    else
        print_warning "⚠️ Site response test inconclusive"
        echo "  - Site responsiveness: Unknown" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
    fi
    
    echo "" >> /home/keithaumiller/stlouisintegration.com/cache-status.md
}

# Main execution
echo "=== Comprehensive Cache Disabling Script ==="
echo "Processing all three Drupal sites with complete cache elimination..."

# Initialize the results file
cat > /home/keithaumiller/stlouisintegration.com/cache-status.md << 'EOF'
# Comprehensive Cache Disabling Results

This file shows the status of all caching mechanisms after running comprehensive-cache-disable.sh

EOF

# Define site configurations - process all three sites
declare -A sites
sites["stlouisintegration"]="St. Louis Integration:80"
sites["forseti"]="Forseti Safety:8080"
sites["theoryofconspiracies"]="Theory of Conspiracies:8081"

# Process each site
for site_dir in "${!sites[@]}"; do
    IFS=':' read -r site_name port <<< "${sites[$site_dir]}"
    
    echo ""
    print_step "=== Processing $site_name (Port $port) ==="
    
    # Step 1: Create comprehensive settings.local.php
    create_comprehensive_settings_local "$site_dir" "$site_name" "$port"
    
    # Step 2: Disable Drupal caching
    disable_drupal_caching "$site_dir" "$site_name" "$port"
    
    # Step 3: Force delete cache files
    force_delete_cache_files "$site_dir" "$site_name"
    
    # Step 4: Verify settings
    verify_cache_settings "$site_dir" "$site_name" "$port"
done

# Global cache clearing
print_step "=== Global Cache Clearing ==="

# Clear system-wide cache files
print_check "Clearing system-wide cache directories..."
find /home/keithaumiller/stlouisintegration.com -type d -name "*cache*" -exec sudo rm -rf {} + 2>/dev/null || true
find /home/keithaumiller/stlouisintegration.com -type d -name "*twig*" -exec sudo rm -rf {} + 2>/dev/null || true

# Restart Apache
print_step "Restarting Apache to ensure all settings take effect..."
sudo service apache2 restart

echo ""
echo "=== COMPREHENSIVE SUMMARY ==="
print_status "✅ All three sites processed successfully"
print_status "✅ All cache mechanisms disabled"
print_status "✅ Settings.local.php created for all sites"
print_status "✅ All cache files deleted"
print_status "✅ Apache restarted"
print_status "✅ Cache status logged to cache-status.md"

echo ""
print_step "=== TEST YOUR CHANGES ==="
echo "St. Louis Integration: curl -s \"http://localhost/amisafe\" | grep -c \"Crime Map\""
echo "Forseti Safety: curl -s \"http://localhost:8080/\" | grep -c \"Philadelphia\""
echo "Theory of Conspiracies: curl -s \"http://localhost:8081/\" | grep -c \"html\""

echo ""
print_step "=== USAGE FOR FRONTEND UPDATES ==="
echo "Run this script after ANY frontend template changes:"
echo "bash /home/keithaumiller/stlouisintegration.com/script/comprehensive-cache-disable.sh"

echo ""
print_warning "Template changes should now take effect IMMEDIATELY without manual cache clearing"