<?php

namespace Drupal\dungeoncrawler_content\Controller;

use Drupal\Core\Controller\ControllerBase;

/**
 * Controller for the How to Play page.
 */
class HowToPlayController extends ControllerBase {

  /**
   * Display the how to play guide.
   *
   * @return array
   *   A render array for the how to play page.
   */
  public function index() {
    $build = [];

    $build['intro'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['how-to-play-intro', 'mb-5']],
      'content' => [
        '#markup' => '<div class="card bg-dark text-light border-primary">
          <div class="card-body">
            <h2 class="card-title">Welcome, Adventurer!</h2>
            <p class="lead">Dungeon Crawler Life is an AI-powered, procedurally generated dungeon crawling RPG. Every adventure is unique, every encounter is different.</p>
          </div>
        </div>',
      ],
    ];

    $build['guides'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['gameplay-guides', 'accordion', 'mb-4']],
      '#prefix' => '<div class="accordion" id="howToPlayAccordion">',
      '#suffix' => '</div>',
    ];

    // Gameplay guides
    $guides = [
      [
        'id' => 'getting-started',
        'title' => '🎮 Getting Started',
        'content' => '<ol class="list-group list-group-numbered">
          <li class="list-group-item">Create your character by choosing a class, race, and rolling stats</li>
          <li class="list-group-item">Each class has unique abilities and playstyles</li>
          <li class="list-group-item">Your starting equipment is determined by your class</li>
          <li class="list-group-item">Choose your starting hex on the world map</li>
          <li class="list-group-item">Begin your adventure!</li>
        </ol>',
      ],
      [
        'id' => 'character-classes',
        'title' => '⚔️ Character Classes',
        'content' => '<div class="row g-3">
          <div class="col-md-6">
            <h5>Fighter</h5>
            <p>Masters of weapons and armor, fighters are versatile warriors who excel in direct combat.</p>
          </div>
          <div class="col-md-6">
            <h5>Wizard</h5>
            <p>Wielders of arcane magic, wizards command powerful spells that can devastate foes.</p>
          </div>
          <div class="col-md-6">
            <h5>Cleric</h5>
            <p>Divine champions who balance healing allies with smiting enemies using holy power.</p>
          </div>
          <div class="col-md-6">
            <h5>Rogue</h5>
            <p>Cunning thieves and scouts who rely on stealth, agility, and precision strikes.</p>
          </div>
        </div>',
      ],
      [
        'id' => 'combat',
        'title' => '⚡ Combat System',
        'content' => '<ul class="list-group">
          <li class="list-group-item"><strong>Turn-based:</strong> Combat proceeds in rounds, with each participant taking turns</li>
          <li class="list-group-item"><strong>Actions:</strong> Attack, cast spells, use items, or defend</li>
          <li class="list-group-item"><strong>Hit Points:</strong> When reduced to 0 HP, you fall unconscious</li>
          <li class="list-group-item"><strong>Critical Hits:</strong> Natural 20s deal double damage</li>
          <li class="list-group-item"><strong>Strategy:</strong> Use terrain, positioning, and party synergy to your advantage</li>
        </ul>',
      ],
      [
        'id' => 'exploration',
        'title' => '🗺️ Dungeon Exploration',
        'content' => '<p>The dungeon is procedurally generated, meaning each journey is unique:</p>
        <ul class="list-group">
          <li class="list-group-item">Rooms are generated by AI with unique layouts and challenges</li>
          <li class="list-group-item">Search for hidden treasures and secret passages</li>
          <li class="list-group-item">Encounter AI-generated creatures with unique abilities</li>
          <li class="list-group-item">Solve puzzles and overcome traps</li>
          <li class="list-group-item">Find and complete dynamic quests for rewards</li>
        </ul>',
      ],
      [
        'id' => 'items',
        'title' => '💎 Items & Equipment',
        'content' => '<p>Discover powerful gear to enhance your character:</p>
        <ul class="list-group">
          <li class="list-group-item"><strong>Weapons:</strong> Swords, axes, bows, staves, and more</li>
          <li class="list-group-item"><strong>Armor:</strong> Protection for head, body, hands, and feet</li>
          <li class="list-group-item"><strong>Potions:</strong> Healing, mana, and status effect remedies</li>
          <li class="list-group-item"><strong>Magical Items:</strong> Unique artifacts with special powers</li>
          <li class="list-group-item"><strong>Rarity:</strong> Common, Uncommon, Rare, Epic, and Legendary tiers</li>
        </ul>',
      ],
      [
        'id' => 'progression',
        'title' => '📈 Character Progression',
        'content' => '<ul class="list-group">
          <li class="list-group-item">Gain experience points (XP) from defeating enemies and completing quests</li>
          <li class="list-group-item">Level up to increase your stats and unlock new abilities</li>
          <li class="list-group-item">Each class has unique skill trees and progression paths</li>
          <li class="list-group-item">Find spell scrolls and tomes to learn new magic</li>
          <li class="list-group-item">Improve your gear through enchantments and upgrades</li>
        </ul>',
      ],
    ];

    foreach ($guides as $index => $guide) {
      $show = $index === 0 ? 'show' : '';
      $collapsed = $index === 0 ? '' : 'collapsed';
      $expanded = $index === 0 ? 'true' : 'false';

      $build['guides'][] = [
        '#markup' => '<div class="accordion-item bg-dark text-light">
          <h2 class="accordion-header">
            <button class="accordion-button bg-dark text-light ' . $collapsed . '" type="button" data-bs-toggle="collapse" data-bs-target="#collapse' . $guide['id'] . '" aria-expanded="' . $expanded . '" aria-controls="collapse' . $guide['id'] . '">
              ' . $guide['title'] . '
            </button>
          </h2>
          <div id="collapse' . $guide['id'] . '" class="accordion-collapse collapse ' . $show . '" data-bs-parent="#howToPlayAccordion">
            <div class="accordion-body">
              ' . $guide['content'] . '
            </div>
          </div>
        </div>',
      ];
    }

    $build['tips'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['tips', 'mt-5']],
      'content' => [
        '#markup' => '<div class="card bg-success text-light">
          <div class="card-body">
            <h3 class="card-title">💡 Pro Tips</h3>
            <ul>
              <li>Save often - the dungeon is unforgiving</li>
              <li>Explore thoroughly - hidden treasures are everywhere</li>
              <li>Balance your party composition for different challenges</li>
              <li>Pay attention to creature behaviors - they adapt to your tactics</li>
              <li>Read item descriptions carefully - some have hidden effects</li>
              <li>Don\'t be afraid to retreat and rest when needed</li>
            </ul>
          </div>
        </div>',
      ],
    ];

    $build['cta'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['cta', 'mt-4', 'text-center']],
      'content' => [
        '#markup' => '<a href="/characters/create" class="btn btn-primary btn-lg">Start Your Adventure</a>',
      ],
    ];

    $build['#attached']['library'][] = 'dungeoncrawler_content/game-cards';

    return $build;
  }

}
