<?php

namespace Drupal\dungeoncrawler_content\Controller;

use Drupal\Core\Controller\ControllerBase;

/**
 * Controller for the World/Lore page.
 */
class WorldController extends ControllerBase {

  /**
   * Display the world and lore information.
   *
   * @return array
   *   A render array for the world page.
   */
  public function index() {
    $build = [];

    $build['intro'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['world-intro', 'mb-5']],
      'content' => [
        '#markup' => '<div class="card bg-dark text-light border-warning">
          <div class="card-body">
            <h2 class="card-title">The Living Dungeon</h2>
            <p class="lead">An ever-evolving realm where AI breathes life into every shadow, creature, and treasure.</p>
          </div>
        </div>',
      ],
    ];

    $build['lore'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['world-lore', 'row', 'g-4']],
    ];

    // World sections
    $sections = [
      [
        'title' => 'The Endless Depths',
        'icon' => '🏛️',
        'content' => 'Deep beneath the surface world lies a dungeon that defies comprehension. Its corridors shift and change, rooms appear and disappear, and each chamber holds secrets both ancient and newly born. The dungeon itself seems alive, responding to the presence of adventurers, adapting to their tactics, learning from their victories.',
      ],
      [
        'title' => 'AI-Born Creatures',
        'icon' => '🐉',
        'content' => 'The denizens of this dungeon are no mere beasts. Each creature is generated by powerful magic, given form and purpose by arcane intelligences beyond mortal understanding. They possess unique abilities, behaviors, and even personalities. No two encounters are ever quite the same.',
      ],
      [
        'title' => 'Procedural Treasures',
        'icon' => '⚔️',
        'content' => 'The weapons, armor, and artifacts found within are crafted by the same mystical forces that shape the dungeon. Each item tells a story, bears unique enchantments, and carries the echo of adventures past. What you find today may never appear again.',
      ],
      [
        'title' => 'Dynamic Quests',
        'icon' => '📜',
        'content' => 'The dungeon itself seems to issue challenges to those who dare explore it. Quest objectives emerge from the shadows, tasks appear as if written by an unseen hand. Complete them to earn the favor of whatever intelligence governs this place.',
      ],
      [
        'title' => 'The Hex Realm',
        'icon' => '🗺️',
        'content' => 'The world above is divided into hexagonal regions, each with its own character and dangers. From frozen wastes to volcanic hellscapes, from haunted forests to crystalline caverns. Travel between them to discover new challenges and opportunities.',
      ],
      [
        'title' => 'Living History',
        'icon' => '📚',
        'content' => 'Every action leaves its mark. Defeated bosses are recorded in the halls of legend. Heroic deeds echo through time. The dungeon remembers, and so do its inhabitants. Your choices shape not just your story, but the story of all who venture here.',
      ],
    ];

    foreach ($sections as $section) {
      $build['lore'][] = [
        '#type' => 'container',
        '#attributes' => ['class' => ['col-md-6', 'col-lg-4']],
        'card' => [
          '#markup' => '<div class="card h-100 bg-dark text-light border-secondary">
            <div class="card-body">
              <h3 class="card-title">
                <span class="display-4">' . $section['icon'] . '</span>
                ' . $section['title'] . '
              </h3>
              <p class="card-text">' . $section['content'] . '</p>
            </div>
          </div>',
        ],
      ];
    }

    $build['call_to_action'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['cta', 'mt-5', 'text-center']],
      'content' => [
        '#markup' => '<div class="card bg-warning text-dark">
          <div class="card-body">
            <h3 class="card-title">Ready to Begin Your Journey?</h3>
            <p class="card-text">Create your character and step into the unknown.</p>
            <a href="/characters/create" class="btn btn-dark btn-lg">Create Character</a>
          </div>
        </div>',
      ],
    ];

    $build['#attached']['library'][] = 'dungeoncrawler_content/game-cards';

    return $build;
  }

}
